[csv]
blacklist_regexes = [
    # All caps means probably BEEP etc.
    '[A-Z\s]+',
    # [ Beeping ] etc.
    # [ Beeping ] [ Whistling ] etc.
    '(\[[\w\s]+\]\s?)*'
]
[[csv.try_replace]]
original = 'R2'
replace = 'Artoo'

[json]
